site_name: Incus Python SDK
site_description: A Python SDK for the Incus API
site_author: Incus SDK Team
repo_url: https://github.com/orbical-dev/incus_sdk
repo_name: orbical-dev/incus_sdk
site_url: https://orbical-dev.github.io/incus_sdk/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - API Reference:
    - Overview: api/index.md
    - Models: api/models.md
  - Examples: examples.md
  - Error Handling: error_handling.md
  - Contributing: contributing.md
  - Changelog: changelog.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
  - tags
