site_name: Incus Python SDK
site_description: A Python SDK for the Incus API
site_author: Incus SDK Team
repo_url: https://github.com/orbical-dev/incus_sdk
theme: readthedocs

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - API Reference:
    - Overview: api/index.md
    - Models: api/models.md
  - Examples: examples.md
  - Error Handling: error_handling.md
  - Contributing: contributing.md
  - Changelog: changelog.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
